# Semantic Ising Simulator - Default Configuration
# v0.2 API locked

# Temperature sweep parameters
temperature_range: [0.1, 10.0]
temperature_steps: 50 # Default number of temperature steps

# Default encoder model
default_encoder: "sentence-transformers/LaBSE"

# Supported languages for multilingual experiments
supported_languages: ["en", "fr", "es", "de", "it", "pt", "nl", "ru", "zh", "ja", "af", "am", "ar", "az", "be", "bg", "bn", "bs", "ca", "cs", "cy", "da", "el", "et", "fa", "fi", "ga", "gl", "gu", "he", "hi", "hr", "hu", "hy", "id", "is", "ka", "kk", "km", "kn", "ku", "ky", "la", "lo", "lt", "lv", "mk", "ml", "mn", "mr", "ms", "my", "ne", "no", "pa", "pl", "ro", "sk", "sl", "sq", "sr", "su", "sv", "ta", "te", "th", "tl", "tr", "uk", "ur", "vi", "xh", "yi", "yo", "zu"]

# Anchor configuration
anchor_config:
  default_anchor_language: "en"
  include_anchor_default: false

# Vector storage options
store_all_temperatures: true

# UMAP parameters
umap_params:
  n_neighbors: 15
  min_dist: 0.1
  n_components: 2
  random_state: 42

# Simulation parameters (road-tested for 25-lang LaBSE)
simulation_params:
  max_iterations: 6000  # Increased from 1000
  convergence_threshold: 3e-3  # Relaxed from 1e-6
  energy_coupling: 1.0
  update_method: "metropolis"  # Options: "metropolis", "glauber"
  noise_sigma: 0.04  # Reduced from 0.1 to prevent overshooting
  steps_per_T: 6000  # Increased steps per temperature
  eps: 0.003  # Relaxed convergence tolerance

# Clustering parameters
cluster_params:
  similarity_threshold: 0.8  # Base threshold (actual threshold varies with temperature: 0.8-0.95)
  min_cluster_size: 1

# Correlation analysis parameters
lambda_distance: 0.5  # Exponential decay parameter for linguistic distance weighting 